[project]
name = "diesdas"
version = "0.1.0"
description = "Add a short description here"
authors = ["Moritz Wilksch <moritz.wilksch@quantco.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
numpy = ">=1.26.4,<1.27"
polars = ">=0.20.19,<0.21"

[feature.dev.dependencies]
pyright = ">=1.1.358,<1.2"
ruff = ">=0.3.5,<0.4"
ruff-lsp = ">=0.0.53,<0.1"
ipython = ">=8.4.0,<8.23"

[feature.dev.tasks]
pre-commit = "ruff check --fix . && mypy ."

[environments]
dev = ["dev"]
